- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Install Helm
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Install helm-git plugin
  command: helm plugin install https://github.com/aslafy-z/helm-git
  args:
    creates: ~/.local/share/helm/plugins/helm-git
  environment:
    HELM_PLUGINS: "{{ ansible_env.HOME }}/.local/share/helm/plugins"